In [1]:
import pandas

In [2]:
dm = pandas.read_csv('2010game_physical.csv')

In [21]:
dm['awayWin'] = dm.apply(lambda x: 1 if x['awayTeam']==x['winteamcode'] else 0, 1)
dm['homeWin'] = dm.apply(lambda x: 1 if x['awayTeam']!=x['winteamcode'] else 0, 1)

dm.head()

,gamenumber,awayTeam,awaySalary,awayAge,awayHeight,awayWeight,awayGoaliue,awayGoals,homeTeam,homeSalary,homeAge,homeHeight,homeWeight,homeGoalie,homeGoals,winteamcode,awayWin,homeWin
0,20001,MTL,38.383301,501,1313,3695,PRICE_CAREY,2,TOR,44.612999,471,1312,3715,GIGUERE_JEANSEBASTIEN,3,TOR,0,1
1,20002,PHI,50.365002,498,1317,3669,BOBROVSKY_SERGEI,3,PIT,49.192402,497,1308,3611,FLEURY_MARCANDRE,2,PHI,1,0
2,20003,CAR,35.825001,471,1315,3574,WARD_CAM,4,MIN,40.180000,503,1321,3734,BACKSTROM_NIKLAS,3,CAR,1,0
3,20004,CHI,50.560001,462,1326,3700,TURCO_MARTY,3,COL,33.750000,469,1306,3627,ANDERSON_CRAIG,4,COL,0,1
4,20005,CGY,39.764999,505,1331,3726,KIPRUSOFF_MIIKKA,0,EDM,41.400002,458,1324,3745,KHABIBULIN_NIKOLAI,4,EDM,0,1

In [33]:
da = dm.groupby(['awayTeam'], as_index=False)['awayGoals', 'homeGoals', 'awayWin', 'homeWin'].agg('sum')
da = da.rename(columns={'awayTeam': 'Team', 'awayGoals': 'GoalsFor', 'homeGoals': 'GoalsAllowed', 'awayWin': 'Wins', 'homeWin': 'Losses'})

dh = dm.groupby(['homeTeam'], as_index=False)['awayGoals', 'homeGoals', 'awayWin', 'homeWin'].agg('sum')
dh = dh.rename(columns={'homeTeam': 'Team', 'awayGoals': 'GoalsAllowed', 'homeGoals': 'GoalsFor', 'homeWin': 'Wins', 'awayWin': 'Losses'})

ds = da.append(dh)
ds = ds[['Team', 'GoalsFor', 'GoalsAllowed', 'Wins', 'Losses']]
ds = ds.groupby(['Team'], as_index=False).sum()
ds['GamesPlayed'] = ds.Wins + ds.Losses
ds = ds[['Team', 'GamesPlayed', 'GoalsFor', 'GoalsAllowed', 'Wins', 'Losses']]
ds.to_csv('NHL_season_team_goals.csv')